name: Deploy to Heroku

on:
  push:
    branches:
      - heroku-setup  # Set this to your default bran

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pushes and releases the image on heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:login
        heroku container:push web --app forecast-genius
        heroku container:release web --app forecast-genius
